# Generated by Django 3.1.4 on 2020-12-04 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(choices=[('NRV', 'Nervoso'), ('MTA', 'MartenssonA'), ('MTB', 'MartenssonB'), ('MLA', 'MolicelleA'), ('MLB', 'MolicelleB'), ('MSN', 'Maisonettes'), ('CH1', 'Chiodo1'), ('CH2', 'Chiodo2'), ('MON', 'Monaci'), ('SNG', 'SanGennaro')], default='MTA', max_length=3)),
                ('room_type', models.CharField(choices=[('SIN', 'Single'), ('DBL', 'Double')], default='SIN', max_length=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
