# Generated by Django 3.1.4 on 2020-12-15 18:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_house_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allocation',
            new_name='Reservation',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='student',
            new_name='user',
        ),
    ]
