# Generated by Django 3.1.4 on 2021-01-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_house_reservation', '0002_auto_20201215_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='neighborhood',
            field=models.CharField(choices=[('NRV', 'Nervoso'), ('MTA', 'MartenssonA'), ('MTB', 'MartenssonB'), ('MLA', 'MolicelleA'), ('MLB', 'MolicelleB'), ('MSN', 'Maisonettes'), ('CH1', 'Chiodo1'), ('CH2', 'Chiodo2'), ('MON', 'Monaci'), ('SNG', 'SanGennaro')], max_length=3),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('SIN', 'Single'), ('DBL', 'Double')], max_length=3),
        ),
    ]
