# Generated by Django 3.1.4 on 2020-12-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(choices=[('NRV', 'Nervoso'), ('MTA', 'MartenssonA'), ('MTB', 'MartenssonB'), ('MLA', 'MolicelleA'), ('MLB', 'MolicelleB'), ('MSN', 'Maisonettes'), ('CH1', 'Chiodo1'), ('CH2', 'Chiodo2'), ('MON', 'Monaci'), ('SNG', 'SanGennaro')], default='MTA', max_length=3)),
                ('room_type', models.CharField(choices=[('SIN', 'Single'), ('DBL', 'Double')], default='SIN', max_length=3)),
            ],
        ),
    ]
