# Generated by Django 3.1.4 on 2020-12-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allocations',
            new_name='Allocation',
        ),
    ]
