# Generated by Django 3.1.4 on 2020-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='neighborhood',
            field=models.CharField(choices=[('NRV', 'Nervoso'), ('MTA', 'MartenssonA'), ('MTB', 'MartenssonB'), ('MLA', 'MolicelleA'), ('MLB', 'MolicelleB'), ('MSN', 'Maisonettes'), ('CH1', 'Chiodo1'), ('CH2', 'Chiodo2'), ('MON', 'Monaci'), ('SNG', 'SanGennaro')], max_length=3),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='room_type',
            field=models.CharField(choices=[('SIN', 'Single'), ('DBL', 'Double')], max_length=3),
        ),
    ]
